language: php
php:
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

before_script:
  - composer install

script:
  - travis_retry composer test
